### ISSUE TITLE
Error el scrip se sale 

### ISSUE THREAD

**Issue by AxelRuizz** [CodigoCristo/arcris#11]
Ya ejecutado el scrip y estando en la ventana de seleccionar si quiero instalar limpio o hacer instalacion junto a Windows cuando selecciono cualquier opción el scrip se sale

**Comment by jcanca** [comment]
Me pasa lo mismo...

**Comment by AxelRuizz** [comment]
> Me pasa lo mismo...

lo solucionaste o algo?

**Comment by hwqduqdwdwq** [comment]
Me pasó igual 
![image](https://user-images.githubusercontent.com/38401587/142761243-0918b310-c5ba-4844-af5c-988a6bda6ded.png)

**Comment by JjersaR** [comment]
Pensé que era error de loadkeys pero ya ví que no, hace unos meses lo lo había descargado sin problemas pero ahora no puedo ejecutar el script

**Comment by JjersaR** [comment]
No sé si les sirva, pero usaré este script 
https://github.com/helmuthdu/aui
Usaré este video, por si les sirve:
https://youtu.be/Dlhi0mFyv4Q
