### ISSUE TITLE
cuando instalas con gnome no instala adecuadamente xorg

### ISSUE THREAD

**Issue by Vertecedoc4545** [CodigoCristo/arcris#3]
Cuando instalas con gnome no instala adecuadamente xorg y lo tienes que volver a instalar y configurar para que funcione

**Comment by CodigoCristo** [comment]
Voy hacer una prueba con gnome, los paquetes que instalo es minimalista, son : gnome-shell gdm gnome-control-center gnome-backgrounds gnome-tweaks
