### ISSUE TITLE
Error!!! Script

### ISSUE THREAD

**Issue by MeXinuX** [CodigoCristo/arcris#7]
He intentado usar el script y al darle "wget is.gd/arcris ; sh arcris" me sale sh: arcris-install.sh No such file or directory

**Comment by JoakoV3** [comment]
Me pasa exactamente lo mismo y he usado este script antes y ha funcionado perfectamente, pero desde este [Commit](https://github.com/CodigoCristo/arcris/commit/742732b40c129f77dd1ff6403484ddc0ce9beb26) no funciona y  me puse a investigar y creo que es por el tipo de archivo que se descarga que es .tar.xz que no lo puede extraer.

**Comment by Jorgvica** [comment]
Me pasa exactamente lo mismo, espero que lo arregle.

**Comment by zelig-auditore** [comment]
> He intentado usar el script y al darle "wget is.gd/arcris ; sh arcris" me sale sh: arcris-install.sh No such file or directory

Ese error se resuelve clonando el repo de git y ejecutando el script, pero vienen mas errores que al parecer son causados por una actualización de pacman.

- advertencia: archivo de configuración /etc/pacman.conf, linea 35: directiva ""TotalDownload"" en seccion "options" no reconocida

- yay: error while loading shared libraries: libalpm.so.12: cannot open shared object file: no such file or directory

Al final solo se instala el sistema base (Sin WM, DE)

**Comment by MeXinuX** [comment]
> > He intentado usar el script y al darle "wget is.gd/arcris ; sh arcris" me sale sh: arcris-install.sh No such file or directory
> 
> Ese error se resuelve clonando el repo de git y ejecutando el script, pero vienen mas errores que al parecer son causados por una actualización de pacman.
> 
> * advertencia: archivo de configuración /etc/pacman.conf, linea 35: directiva ""TotalDownload"" en seccion "options" no reconocida
> * yay: error while loading shared libraries: libalpm.so.12: cannot open shared object file: no such file or directory
> 
> Al final solo se instala el sistema base (Sin WM, DE)



> > He intentado usar el script y al darle "wget is.gd/arcris ; sh arcris" me sale sh: arcris-install.sh No such file or directory
> 
> Ese error se resuelve clonando el repo de git y ejecutando el script, pero vienen mas errores que al parecer son causados por una actualización de pacman.
> 
> * advertencia: archivo de configuración /etc/pacman.conf, linea 35: directiva ""TotalDownload"" en seccion "options" no reconocida
> * yay: error while loading shared libraries: libalpm.so.12: cannot open shared object file: no such file or directory
> 
> Al final solo se instala el sistema base (Sin WM, DE)

Si eso me pasaba Antes de que me saliera el error que menciona se instalaba solo el sistema base,sin DE,WM y si creo el error lo causa pacman por que tenia instalado arch y al instalar las actualizaciones decía que no tenia yay y pamac instalado

**Comment by JoakoV3** [comment]
El script ya esta arreglado, es necesario poner  ``loadkeys es`` para que funcione, tal cual lo dice la documentacion.
