### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by AxelRuizz** [CodigoCristo/arcris#8]
Al ejecutar "wget is.gd/arcris" muestra  resolving is.gd (Is.gd)... failed: Name or service  not known.  Wget: unable yo resolve host address is.gd ¿Que procede?

**Comment by CodigoCristo** [comment]
Murió is.gd D: 

clona el repositorio con git

pacman -Sy git 

git clone https://github.com/CodigoCristo/arcris.git

cd arcris
sh arcris

**Comment by AxelRuizz** [comment]
Gracias 😊
